name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build packages
        run: yarn build

      - name: Test packages
        run: yarn test

  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}
